name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
